---
- name: Retrieve admin credentials for Windows
  hosts: localhost
  gather_facts: no
  tasks:
  - name: add instance host with machine credential in inventory
    add_host:
      name: "instance"
      admin_username: "{{ansible_user}}"
      admin_password: "{{ansible_password}}"

- name: aws_create_vm
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - files/aws_vars

  tasks:
  - name: create an ec2 key pair
    ec2_key:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region }}"
      name: "ansible"
    register: ec2key
    
  - name: Set up Security Group
    ec2_group:
      name: "mysecgrp"
      description: sg with rule descriptions
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region }}"
      rules:
      - proto: tcp
        ports:
        - 5986
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on WinRM-HTTPS
      - proto: tcp
        ports:
        - 3389
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on RDP
 
  - name: Provision an instance
    ec2:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      key_name: "ansible"
      id: "{{ vm_name }}"
      instance_type: t2.micro
      image: "ami-0182e552fba672768"
      region: "{{ aws_region }}"
      group: "mysecgrp"
      wait: true
      instance_tags:
        Name: "{{ vm_name }}"
      user_data: "{{ lookup('file', 'files/sysprep') }}"
    register: ec2_instance
      
  - name: Get the Windows Password of the administrator
    ec2_win_password:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      instance_id: "{{ ec2.instance_ids[0] }}"
      region: "{{ aws_region }}"
      key_data: "{{ ec2key.key.private_key }}"
      wait: true
    register: win_pwd

  - name: delete the ec2 key pair
    ec2_key:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      region: "{{ aws_region }}"
      name: "ansible"
      state: absent
      
- name: add ansible machine credential to instance
  hosts: "{{ ec2_instance.public_ip }}"
  gather_facts: no
  vars:
    ansible_user: "ansible"
    ansible_password: "{{ win_pwd.win_password }}"
    
  tasks:
  - name: add windows admin account for ansible
    win_user:
      name: '{{ hostvars["instance"].admin_username }}'
      password: '{{ hostvars["instance"].admin_password }}'
      state: present
      groups:
      - Administrators
