- name: aws_create_vm
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - files/aws_vars

  tasks:
  - name: create an ec2 key pair
    ec2_key:
      name: ansible
    register: ec2key
    
  - name: Set up Security Group
    ec2_group:
      name: "mysecgrp"
      description: sg with rule descriptions
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
#      vpc_id: vpc-xxxxxxxx
#      profile: "{{ aws_profile }}"
      region: "{{ aws_region }}"
      rules:
      - proto: tcp
        ports:
        - 5986
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on WinRM-HTTPS
 
  - name: Provision an instance
    ec2:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
      key_name: "ansible"
      id: "{{ vm_name }}"
      instance_type: t2.micro
      image: "ami-0182e552fba672768"
      region: "{{ aws_region }}"
      group: "mysecgrp"
      wait: true
      instance_tags:
        Name: "{{ vm_name }}"
      user_data: "{{ lookup('file', 'files/sysprep') }}"
    register: ec2
      
  - name: dump the key
    debug:
      var: ec2key
      
  - name: Get the Windows Password of the administrator
    ec2_win_password:
      aws_access_key: "{{ aws_access_key_id }}"
      aws_secret_key: "{{ aws_secret_access_key }}"
#      profile: my-boto-profile
      instance_id: "{{ ec2.instance_ids[0] }}"
      region: "{{ aws_region }}"
      key_data: "{{ ec2key.key.private_key }}"
#      key_file: "files/test.pem"
      wait: true
    register: win_pwd

  - name: Show the password
    debug:
      var: win_pwd
